image: node:12.13.1

cache:
  paths:
    - node_modules/
    - .yarn

before_script:
  - yarn install

pages:
  stage: deploy
  script:
    - CI=true yarn run build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - master
